# Generated by Django 4.1.4 on 2022-12-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0002_alter_file_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="default")),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_associated",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pdfs.file"
                    ),
                ),
            ],
        ),
    ]
